GWG/urls.py
from django.urls import path
from GWG.views import *

app_name = "GWG"


urlpatterns = [
    path("", welcome, name="welcome"),
    path("aboutus", aboutus, name="aboutus"),
    path("new-user", registrationForm, name="registrationForm"),
    path("store-user", registered, name="storeUser"),
    path("login", login, name="login"),
    path("home", homePage, name="home"),
    path("profile", profile, name="profile"),
    path("deleteUser", deleteUser, name="deleteUser"),
    path("userDetails", userDetails, name="userDetails"),
    path("deleteQue", deleteQue, name="deleteQue"),
    path("editProfile", editProfile, name="editProfile"),
    path("allProfile", allProfile, name="allProfile"),
    path("set-questions", setQuestions, name="setQuestions"),
    path("show-Questions", showQuestions, name="showQuestions"),
    path("test-Paper", testPaper, name="testPaper"),
    path("calculate-result", calculateTestResult, name="caculateTest"),
    path("showAllResult", showAllResult, name="showAllResult"),
    path("result", showTestResult, name="result"),
    path("logout", logout, name="logout"),
]

MYWEBSITE/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('GWG.urls')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

GWG/models.py
from django.db import models

class User(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    classTh=models.IntegerField(max_length=4)
    email=models.EmailField(null=False,max_length=50)
    mobileNo=models.IntegerField(null=False,max_length=11)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)


class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    classTh=models.IntegerField(max_length=4)
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)


class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    worng=models.IntegerField()
    points=models.FloatField()

GWG/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from GWG.models import *
from django.template import loader
import random


def welcome(request):
    res = render(request, "welcome.html")
    return res


def aboutus(request):
    res = render(request, "aboutus.html")
    return res


def registrationForm(request):
    res = render(request, "registration.html")
    return res


def registered(request):
    if request.method == "POST":
        username = request.POST["username"]
        if len(User.objects.filter(username=username)):
            userStatus = 1
        else:
            user = User()
            user.username = username
            user.password = request.POST["password"]
            user.name = request.POST["name"]
            user.classTh = request.POST["classTh"]
            user.mobileNo = request.POST["mobile"]
            user.email = request.POST["email"]
            user.save()
            userStatus = 2
    else:
        userStatus = 3
    context = {
        "userStatus": userStatus,
    }
    res = render(request, "registered.html", context)
    return res


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = User.objects.filter(username=username, password=password)
        if len(user) == 0:
            loginError = "Invalid Username or password"
            res = render(request, "login.html", {"loginerror": loginError})
        else:
            request.session["username"] = user[0].username
            request.session["name"] = user[0].name
            request.session["firstLetter"] = (user[0].name)[0]
            res = HttpResponseRedirect("home")
    else:
        res = render(request, "login.html")
    return res


def homePage(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        res = render(request, "home.html")
    return res


def profile(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        user = User.objects.filter(username=request.session["username"])
        context = {"user": user}
        res = render(request, "profile.html", context)
    return res

def deleteUser(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        if request.method == "POST":
            username = request.POST["username"]
            if len(User.objects.filter(username=username)):
                user = User.objects.filter(username=request.POST["username"])
                user.delete()
                userStatus = 1
                res = render(request, "deleteuser.html", context)
            else:
                userStatus = 2
            context = {"userStatus": userStatus}
            res = render(request, "deleteuser.html",context)
        else:
            res = render(request, "deleteuser.html")
    return res


def userDetails(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        if request.method == "POST":
            username = request.POST["username"]
            if len(User.objects.filter(username=username)):
                user = User.objects.filter(username=request.session["username"])
                results = Result.objects.filter(username_id=user[0].username)
                userStatus=1
                context = {"user": user[0], "results": results,'userStatus':userStatus}
                res = render(request, "userDetails.html", context)
            else:
                userStatus = 2
                context = {'userStatus':userStatus}
            res = render(request, "userDetails.html",context)
        else:
            res = render(request, "userDetails.html")
    return res


def deleteQue(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        if request.method == "POST":
            qid = request.POST["qid"]
            if len(Question.objects.filter(qid=qid)):
                question = Question.objects.filter(qid=request.POST["qid"])
                question.delete()
                questionStatus = 1
            else:
                questionStatus = 2
            context = {"questionStatus": questionStatus}
            res = render(request, "deleteQue.html",context)
        else:
            res = render(request, "deleteQue.html")
    return res


def allProfile(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        users = User.objects.all()
        context = {"users": users}
        res = render(request, "allProfile.html", context)
    return res


def editProfile(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        if request.method == "POST":
            user = User()
            user.username = request.session["username"]
            user.test_attempted = request.POST["test_attempted"]
            user.points = request.POST["points"]
            user.password = request.POST["password"]
            user.name = request.POST["name"]
            user.classTh = request.POST["classTh"]
            user.email = request.POST["email"]
            user.mobileNo = request.POST["mobile"]
            user.save()
            res = res = HttpResponseRedirect("profile")
        else:
            user = User.objects.filter(username=request.session["username"])
            context = {"user": user}
            res = render(request, "editProfile.html", context)
    return res


def setQuestions(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        questionStatus = 1
        if request.method == "POST":
            question = Question()
            question.classTh = request.POST["classTh"]
            question.que = request.POST["question"]
            question.a = request.POST["optionA"]
            question.b = request.POST["optionB"]
            question.c = request.POST["optionC"]
            question.d = request.POST["optionD"]
            question.ans = request.POST["currectOption"]
            question.save()
            questionStatus = 2
        context = {"questionStatus": questionStatus}
        res = render(request, "setQuestions.html", context)
    return res


def showQuestions(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        if request.method == "POST":
            questions = Question.objects.filter(classTh=request.POST["classTh"])
            context = {
                "questions": questions,
            }
            res = render(request, "showQuestions.html", context)
        else:
            res = render(request, "showQuestions.html")
    return res


def testPaper(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        user = User.objects.filter(username=request.session["username"])
        classth = user[0].classTh
        n = int(request.GET["n"])
        question_pool = list(Question.objects.filter(classTh=classth))
        random.shuffle(question_pool)
        questions_list = question_pool[:n]
        context = {
            "questions": questions_list,
        }
        res = render(request, "test_paper.html", context)
    return res


def calculateTestResult(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        total_attempt = 0
        total_right = 0
        total_wrong = 0
        qid_list = []
        for k in request.POST:
            if k.startswith("qno"):
                qid_list.append(int(request.POST[k]))
        for n in qid_list:
            question = Question.objects.get(qid=n)
            try:
                if question.ans == request.POST["q" + str(n)]:
                    total_right += 1
                else:
                    total_wrong += 1
                total_attempt += 1
            except:
                pass
        points = (total_right - total_wrong) / len(qid_list) * 10
        # store result in result table
        result = Result()
        result.username = User.objects.get(username=request.session["username"])
        result.attempt = total_attempt
        result.right = total_right
        result.worng = total_wrong
        result.points = points
        result.save()
        # Update user Table
        user = User.objects.get(username=request.session["username"])
        user.test_attempted += 1
        user.points = (
            user.points * (user.test_attempted - 1) + points
        ) / user.test_attempted
        user.save()
        res = HttpResponseRedirect("result")
    return res


def showAllResult(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        user = User.objects.filter(username=request.session["username"])
        results = Result.objects.filter(username_id=user[0].username)
        context = {"user": user[0], "results": results}
        res = render(request, "showAllResult.html", context)
    return res


def showTestResult(request):
    if "name" not in request.session.keys():
        res = HttpResponseRedirect("login")
    else:
        # fect lastest result from Result table
        result = Result.objects.filter(
            resultid=Result.objects.latest("resultid").resultid,
            username_id=request.session["username"],
        )
        context = {"result": result}
        res = render(request, "result.html", context)
    return res


def logout(request):
    if "name" in request.session.keys():
        del request.session["username"]
        del request.session["name"]
    res = HttpResponseRedirect("login")
    return res

GWG/templates/allProfile.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>
<div id='report'>
<h1> All profile details. </h1>
</div>

<div class="form">
    {% for u in users %}
    <p>UserName : {{ u.username}}</p><br>
    <p>Name : {{ u.name}}</p><br>
    <p>E-mail : {{ u.email}}</p><br>
    <p>Class : {{ u.classTh}}</p><br>
    <p>Mobile No. : {{ u.mobileNo}}</p><br>
    <p>Test Attempted : {{ u.test_attempted}}</p><br>
    <p>Points : {{ u.points}}</p><br><br><br>
    {% endfor %}

</div>


{% endblock %}

GWG/templates/deleteuser.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>

<div id='report'>
    {% if userStatus == 1 %}
    <span id="questionStatus">Delete User Successfully.</span>
    {% elif userStatus == 2 %}
    <span id="questionStatus">Did not match UserName.</span>
    {% endif %}
    <form action="{% url 'GWG:deleteUser' %}" method="post">
        {% csrf_token %}
        <label for="username">UserName :</label>
        <input type="text" name="username" placeholder="UserName" required>
        <input type="submit" value="Delete">
        <input type="reset" value="reset">
    </form>
</div>

{% endblock %}

GWG/templates/editProfile.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}


<div class="form">
    <h1>{{ request.session.name | upper}}, edit your profile. </h1><br>
    {% for u in user %}
    <form action="{% url 'GWG:editProfile' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="#username">UserName :</label></td>
                <td><input type="text" name="username" id="username" value='{{ u.username}}' required></td>
            </tr>
            <tr>
                <td><label for="#password">Password :</label></td>
                <td><input type="password" name="password" id="password" value="{{u.password}}" required></td>
            </tr>
            <tr>
                <td><label for="#name">Name :</label></td>
                <td><input type="text" name="name" id="name" value="{{u.name}}" required></td>
            </tr>
            <tr>
                <td><label for="#classTh">Class :</label></td>
                <td><input type="number" name="classTh" id="classTh" value="{{u.classTh}}" required></td>
            </tr>
            <tr>
                <td><label for="#email">Email :</label></td>
                <td><input type="email" name="email" value="{{u.email}}" id="email"></td>
            </tr>

            <tr>
                <td><label for="#mobile">Monile No. :</label></td>
                <td><input type="mobile" name="mobile" value="{{u.mobileNo}}" id="mobile"></td>
            </tr>

            <tr>
                <td><input type="reset" value="RESET"></td>
                <td><input type="submit" value="Save"></td>
            </tr>
            <div class="none" style="display: none;">
                <input type="number" name="test_attempted" id="" value="{{u.test_attempted}}">
                <input type="number" name="points" id="" value="{{u.points}}">
            </div>
        </table>
    </form>
    {% endfor %}
</div>


{% endblock %}

GWG/templates/home.html
{% extends 'master.html' %}
{% load static %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout </a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>
<div id='report'>
    <h1>Welcome {{ request.session.name | upper}}, to your home page. </h1>
</div>
<br>

{% if request.session.username == 'Rituraj Kumar' or  request.session.username == 'Ritesh Kumar' or  request.session.username == 'Shibu Kumar' %}
<div class="form">

    <div class="button-link">
        <a href="{% url 'GWG:setQuestions' %}">Set Question</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:showQuestions' %}">Show All Question</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:deleteQue' %}">Delete Question</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:allProfile' %}">Show All Profile</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:userDetails' %}">Users Details</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:deleteUser' %}">Delete Profile</a>
    </div>
</div>

{% endif %}
<br>

<div class="form">
    <!-- <div class="button-link">
        <a href="{% url 'GWG:testPaper' %}?n=1">Test Series 1-1 </a>
    </div> -->
    <div class="button-link">
        <a href="{% url 'GWG:testPaper' %}?n=20">Test Series 20-20 </a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:testPaper' %}?n=50">Test Series 50-50</a>
    </div>
    <div class="button-link">
        <a href="{% url 'GWG:showAllResult' %}">Test History</a>
    </div>
</div>



<div class="all-container">
    <div class="box">
        <div class="system-img">
            <div class="teachers">
                <img src="{% static 'NiteshSir.jpg' %}" alt="NiteshSir">
                <p><b>Director : - Ritesh Sir</b></p>
                <p>Contact No. :- 6200718713</p>
            </div>
             <div class="teachers">
                <img src="{% static 'ShibuSir.jpg' %}" alt="NiteshSir">
                <p>Shibu Sir</p>
                <p>Subject :- Math</p>
            </div>
            <div class="teachers">
                <img src="{% static 'AmitSir.jpg' %}" alt="NiteshSir">
                <p>Amit Sir</p>
                <p>Subject :-Social Science</p>
            </div>
            <div class="teachers">
                <img src="{% static 'NaveenSir.jpg' %}" alt="NiteshSir">
                <p>Naveen Sir</p>
                <p>Subject :- Management</p>
            </div>
            <div class="teachers">
                <img src="{% static 'ShubhamSir.jpg' %}" alt="NiteshSir">
                <p>Shubham Sir</p>
                <p>Subject :- Science</p>
            </div>
        </div>
        <div class="features">
            <h2><b> Key Features :</b></h2>
            <hr>
            <ol type="1">
                <li>
                    <b> Question Banks : </b>
                    A database of question, often categorized by topics,difficulty level,
                    of subject, that allows randomization of question to minimize cheating.
                </li>
                <li>
                    <b>Automated Grading : </b>
                    For multiple-choice or other objective-type questions, answers are
                    automatically graded, reducing manual effort.
                </li>
                <li>
                    <b>Time Management : </b>
                    Built-in timers ensure that students complete the exam within a specified duration.
                </li>
                <li>
                    <b>Security : </b>
                    Many systems include features like browser lockdowns, IP tracking,or AI-based
                    proctoring to prevent cheating.
                </li>
            </ol>
            <h2><b> Benefits :</b></h2>
            <hr>
            <ol type="A">
                <li>
                    <b> Convenience : </b>
                    Students can take exams from anywhere, eliminating the need for physical classrooms.
                </li>
                <li>
                    <b>Cost-Effective : </b>
                    Reduces costs associated with physical exam centers,paper printing, and invigilation.
                </li>
                <li>
                    <b>Immediate Feedback : </b>
                    Automated grading allows for instant feedback, especially for objective qustions.
                </li>
                <li>
                    <b>Scalability : </b>
                    Thousands of students can take exams simulataneously without geographical constraints.
                </li>
                <li>
                    <b>Environmentally Friendly : </b>
                    Reeduces the use of paper and other physical sources.
                </li>
            </ol>
        </div>
    </div>
    <div class="box">
        <div class="features">
            <h2><b>Bihar Board And CBSE Board</b></h2>
            <ol type="A">
                <hr>
                <li>Class :- 8th to 12th</li>
                <li>Admission start</li>
                <li>Basic to Advance</li>
                <li>Hindi Medium And English Medium</li>
                <li>All Subject</li>
                <li>Online Classes And Offline Classes</li>
                <li>Daily Assignment with solution</li>
                <li>Chapterwise test And Miscellaneous test</li>
                <li>Daily live test with Solution</li>
                <li>One Formula book free</li>
                <li>If any student get above 80% marks then he/she will awarded by Institution.</li>
            </ol>
        </div>
        <div class="features">
            <h2><b> Online Exam Services :</b></h2>
            <hr>
            <ol type="1">
                <li>
                    <p>Customizable Exam Creation
                        Design and implement tests tailored to specific subjects, topics, or learning objectives.
                        Features include:
                    </p>
                </li>
                <li>
                    <p>Multiple question types: Multiple Choice, Fill-in-the-Blank, Essay, and True/False.
                    </p>
                </li>
                <li>
                    <p>Randomized questions and options to prevent cheating.
                    </p>
                </li>
                <li>
                    <p>Time limits for controlled test environments.
                    </p>
                </li>
                <li>
                    <p>Automated Evaluation and Grading
                    </p>
                </li>
                <li>
                    <p>
                        Support for large-scale exams with thousands of participants.</p>
                </li>
                <li>
                    <p>
                        Exams accessible on desktops, tablets, and smartphones.
                    </p>
                </li>
            </ol>
            An <b>Online Exam system</b> is a digital platform used to administer test or
            assessments via the internet.It offers an alternative to traditional paper-based exams,
            enabling remote access, flexibillity, and automination of the entire
            examination process. Here are some key features and benefits of an online exam system.
            <br><br>
            <b> "TeachBot" </b> typically refers to an AI-driven chatbot or vitual assistant designed to support
            educational tasks.It can be used in various settings,such as classrooms or online platforms, to
            assist with teaching,tutoring feedback,or facilitating learing experiences.
            <br><br>
        </div>
    </div>



</div>



{% endblock %}

GWG/templates/login.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:welcome' %}">Home</a>
<a href="{% url 'GWG:aboutus' %}">About</a>
<a href="{% url 'GWG:registrationForm' %}">Register</a>
{% endblock %}

{% block content %}
<div class="form">
    <form action="{% url 'GWG:login' %}" method="post">
        {% csrf_token %}
        <div class="form-unit">
            <label for="#username">UserName :</label>
            <input type="text" name="username" id="username" placeholder="UserName">
        </div>

        <div class="form-unit">
            <label for="#password">Password :</label>
            <input type="password" name="password" id="password" placeholder="Password">
        </div>

        <div class="form-unit">
            <input type="reset" value="RESET">
            <input type="submit" value="SUBMIT">
        </div>
    </form>
   <p style="text-align: center;"> Don't have an Account? <a href="{% url 'GWG:registrationForm' %}"> Register</a></p>
</div>

{% endblock %}

GWG/templates/profile.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>

<div class="form">
    <h1> {{ request.session.name | upper}}, your profile page. </h1><br>
   <p> <a href="{% url 'GWG:editProfile' %}" id="editbtn"> Edit Profile</a></p><br><br><br>
    {% for u in user %}
    <p>UserName : {{ u.username}}</p><br>
    <p>Name : {{ u.name}}</p><br>
    <p>E-mail : {{ u.email}}</p><br>
    <p>Class : {{ u.classTh}}</p><br>
    <p>Mobile No. : {{ u.mobileNo}}</p><br>
    <p>Test Attempted : {{ u.test_attempted}}</p><br>
    <p>Points : {{ u.points}}</p><br>
    {% endfor %}

</div>


{% endblock %}

GWG/templates/registered.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:welcome' %}">Home</a>
<a href="{% url 'GWG:aboutus' %}">About</a>
<a href="{% url 'GWG:registrationForm' %}">Register</a>
<a href="{% url 'GWG:login' %}">Login</a>
{% endblock %}

{% block content %}

{% if userStatus  == 1 %}
<div class='form'>
<div class="userStatus">
    Sorry, username already, please try different username.
    <a href="{% url 'GWG:registrationForm' %}">Black to Registration form</a>
</div>

{% elif userStatus == 2 %}
<div class="userStatus">
    Congratulation!! , User created successfully
    <a href="{% url 'GWG:login' %}">Login</a>
</div>

{% elif userStatus == 3 %}
<div class="userStatus">
    Opps!! Improper Request
    <a href="{% url 'GWG:registrationForm' %}">Black to Registration form</a>
</div>
</div>
{% endif %}


{% endblock %}

GWG/templates/result.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>
<div id='report'>
    <h1> {{ request.session.name | upper}}, your result. </h1>
</div>
<br>

<table class="table">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in result %}
    <tr>
        <td>{{ r.date }}</td>
        <td>{{r.time }}</td>
        <td>{{r.attempt }}</td>
        <td>{{r.right }}</td>
        <td>{{r.worng }}</td>
        <td>{{r.points }}</td>
    </tr>
    {% endfor %}
</table>

<div class="form">

    {% for q in ques %}
    <span>Question : </span><p>{{ q.que}}</p><br>
    <span>Option A : </span><p>{{ q.a}}</p><br>
    <span>Option B : </span><p>{{ q.b}}</p><br>
    <span>Option C : </span><p>{{ q.c}}</p><br>
    <span>Option D : </span><p>{{ q.d}}</p><br>
    <span>Currect Option : </span><p>{{ q.ans}}</p><br>
    {% endfor %}

</div>




{% endblock %}

GWG/templates/userDetails.html
{% extends 'master.html' %}

{% block menu %}
<a href="{% url 'GWG:home' %}">Home</a>
<a href="{% url 'GWG:logout' %}">Logout</a>
<div>
    <a href="{% url 'GWG:profile' %}">Hi<div class="profile">{{request.session.firstLetter | upper}}</div></a>
</div>
{% endblock %}

{% block content %}

<div class="textSlid">
    <mARquee>
        <font size="8">
            <B>Welcome to Grow With Grades</B>
        </font>
    </mARquee>
</div>

<br>

<div id='report'>

    {% if userStatus == 2 %}
    <span id="questionStatus">Did not match UserName.</span>
    {% endif %}
    <form action="{% url 'GWG:userDetails' %}" method="post">
        {% csrf_token %}
        <label for="username">UserName :</label>
        <input type="text" name="username" placeholder="UserName" required>
        <input type="submit" value="Show Details">
        <input type="reset" value="reset">
    </form>
</div>

{% if userStatus == 1 %}
<div id='report'>
    <h1>Your Report Card</h1>
    <p>Hi <span class="special"> {{user.name | upper}} </span>, you have attempted in total <span
            class="special">{{user.test_attempted }}</span>
        test and you have scored <span class="special"> {{ user.points}}</span>on the scale of 10.</p>
</div>
<table class="table">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>{{ r.date }}</td>
        <td>{{r.time }}</td>
        <td>{{r.attempt }}</td>
        <td>{{r.right }}</td>
        <td>{{r.worng }}</td>
        <td>{{r.points }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}


{% endblock %}